module.exports = {
  apps: [
    {
      name: 'auth',
      script: 'auth-service/dist/main.js',
      env: {
        NODE_ENV: 'production',
        HTTP_PORT: '3001',
        TCP_PORT: '4001',
        MONGODB_URI: process.env.MONGODB_URI,
        JWT_SECRET: process.env.JWT_SECRET,
        JWT_EXPIRY: '7d',
        JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
        JWT_REFRESH_EXPIRY: '30d',
      },
    },
    {
      name: 'users',
      script: 'user-service/dist/main.js',
      env: {
        NODE_ENV: 'production',
        HTTP_PORT: '3002',
        TCP_PORT: '4002',
        MONGODB_URI: process.env.MONGODB_URI,
      },
    },
    {
      name: 'products',
      script: 'product-service/dist/main.js',
      env: {
        NODE_ENV: 'production',
        HTTP_PORT: '3003',
        TCP_PORT: '4003',
        MONGODB_URI: process.env.MONGODB_URI,
      },
    },
    {
      name: 'orders',
      script: 'order-service/dist/main.js',
      env: {
        NODE_ENV: 'production',
        HTTP_PORT: '3004',
        TCP_PORT: '4004',
        MONGODB_URI: process.env.MONGODB_URI,
        PRODUCT_SERVICE_HOST: 'localhost',
        PRODUCT_SERVICE_PORT: '4003',
        NOTIFICATION_SERVICE_HOST: 'localhost',
        NOTIFICATION_SERVICE_PORT: '4006',
      },
    },
    {
      name: 'logistics',
      script: 'logistics-service/dist/main.js',
      env: {
        NODE_ENV: 'production',
        HTTP_PORT: '3005',
        TCP_PORT: '4005',
        MONGODB_URI: process.env.MONGODB_URI,
        NOTIFICATION_SERVICE_HOST: 'localhost',
        NOTIFICATION_SERVICE_PORT: '4006',
      },
    },
    {
      name: 'notifications',
      script: 'notification-service/dist/main.js',
      env: {
        NODE_ENV: 'production',
        HTTP_PORT: '3006',
        TCP_PORT: '4006',
        MONGODB_URI: process.env.MONGODB_URI,
        FCM_SERVER_KEY: process.env.FCM_SERVER_KEY || 'placeholder',
      },
    },
    {
      name: 'chat',
      script: 'chat-service/dist/main.js',
      env: {
        NODE_ENV: 'production',
        HTTP_PORT: '3007',
        TCP_PORT: '4007',
        MONGODB_URI: process.env.MONGODB_URI,
      },
    },
    {
      name: 'reviews',
      script: 'review-service/dist/main.js',
      env: {
        NODE_ENV: 'production',
        HTTP_PORT: '3008',
        TCP_PORT: '4008',
        MONGODB_URI: process.env.MONGODB_URI,
      },
    },
    {
      name: 'payments',
      script: 'payment-service/dist/main.js',
      env: {
        NODE_ENV: 'production',
        HTTP_PORT: '3009',
        TCP_PORT: '4009',
        MONGODB_URI: process.env.MONGODB_URI,
        PAYSTACK_SECRET_KEY: process.env.PAYSTACK_SECRET_KEY || 'placeholder',
        PAYSTACK_BASE_URL: 'https://api.paystack.co',
        ORDER_SERVICE_HOST: 'localhost',
        ORDER_SERVICE_PORT: '4004',
      },
    },
    {
      name: 'gateway',
      script: 'api-gateway/dist/main.js',
      env: {
        NODE_ENV: 'production',
        PORT: '3000',
        JWT_SECRET: process.env.JWT_SECRET,
        AUTH_SERVICE_HOST: 'localhost',
        AUTH_SERVICE_PORT: '4001',
        USER_SERVICE_HOST: 'localhost',
        USER_SERVICE_PORT: '4002',
        PRODUCT_SERVICE_HOST: 'localhost',
        PRODUCT_SERVICE_PORT: '4003',
        ORDER_SERVICE_HOST: 'localhost',
        ORDER_SERVICE_PORT: '4004',
        LOGISTICS_SERVICE_HOST: 'localhost',
        LOGISTICS_SERVICE_PORT: '4005',
        NOTIFICATION_SERVICE_HOST: 'localhost',
        NOTIFICATION_SERVICE_PORT: '4006',
        CHAT_SERVICE_HOST: 'localhost',
        CHAT_SERVICE_PORT: '4007',
        REVIEW_SERVICE_HOST: 'localhost',
        REVIEW_SERVICE_PORT: '4008',
        PAYMENT_SERVICE_HOST: 'localhost',
        PAYMENT_SERVICE_PORT: '4009',
      },
    },
  ],
};
